version: 1.0.0.{build}
branches:
  only:
  - master
build_script:
- Prebuild.exe /target vs2010 /targetframework v4_5 /conditionals ISWIN;NET_4_5
- msbuild Vision.sln /p:Configuration=Debug  /p:DefineConstants="ISWIN;NET_4_5"
artifacts:
- path: VisionSim\bin
  name: Vision